#!/bin/bash

SERVER=$1
RPATH=$2

if [ "$SERVER" == "" ]; then
	echo "Usage:"
	echo "  $0 user@server [<path>]"
	exit 1
fi

if [ "$RPATH" == "" ]; then
	RPATH='~/turtl-release'
fi

rsync -ave ssh webroot/release/ ${SERVER}:${RPATH}

