#!/bin/bash

APP=`realpath .`

pushd $APP/webroot/release >/dev/null || {
	echo "Failed to enter release directory."
	exit 1
}

subdir=$1
version=$2

if [ "$subdir" == "" ] || [ "$version" == "" ]; then
	echo "Usage:"
	echo "  $0 [.|extensions|desktop] <version>"
	exit 1
fi

unversioned=`find $subdir -type f | grep -v version | egrep -v '[0-9]+\.[0-9]+'`

for f in `echo "$unversioned"`; do
	file=`echo $f | sed -r 's|((\.[a-z0-9]{2,3}))+$||i'`
	ext=`echo $f | perl -pe 's|.*?((\.[a-z0-9]{2,3})+)|\1|i'`
	if [ "`echo $f | grep firefox`" != "" ]; then
		version="$version-alpha"
	fi
	new="${file}-${version}${ext}"
	mv $f $new
	echo "Versioned: $new"
done

popd > /dev/null
